name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Test Secret
      run: echo "Token: ${{ secrets.SONAR_TOKEN }}"
      
    - uses: sonarsource/sonarqube-scan-action@v3
      env:
        SONAR_TOKEN: squ_5d5f3f6eb06776925ad366a622c30d5ed04eb2f8
        SONAR_HOST_URL: https://sonarqubevm.zapto.org


#push to trigger workflow
